/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useMemo, useRef } from "react"
import { useGLTF, MeshTransmissionMaterial } from "@react-three/drei"
import { useFrame, useThree } from "@react-three/fiber"
import { useControls } from "leva"

export function Model(props) {
  const { nodes, materials } = useGLTF("/mxk-logo.glb")
  const { viewport } = useThree()
  const model = useRef()

  useFrame((state, delta) => {
    model.current.rotation.x += 0.025 * delta
    model.current.rotation.y -= 0.025 * delta
  })

  const materialProps = useControls({
    thickness: { value: 0.85, min: 0, max: 3, step: 0.05 },

    roughness: { value: 0, min: 0, max: 1, step: 0.1 },

    transmission: { value: 1, min: 0, max: 1, step: 0.1 },

    ior: { value: 1.3, min: 0, max: 3, step: 0.1 },

    chromaticAberration: { value: 0.92, min: 0, max: 1 },

    backside: { value: true },
  })

  return (
    <group {...props} dispose={null} scale={viewport.width / 20} ref={model}>
      <MeshTransmissionMaterial {...materialProps} />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube002.geometry}
        // material={materials.Material}
        position={[0.333, -0.734, 0.043]}
      >
        <MeshTransmissionMaterial {...materialProps} />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube005.geometry}
        // material={materials.Material}
        position={[0.333, -0.734, 0.043]}
      >
        <MeshTransmissionMaterial {...materialProps} />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube006.geometry}
        // material={materials.Material}
        position={[0.333, -0.734, 0.043]}
      >
        <MeshTransmissionMaterial {...materialProps} />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube007.geometry}
        // material={materials.Material}
        position={[0.333, -0.734, 0.043]}
      >
        <MeshTransmissionMaterial {...materialProps} />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube009.geometry}
        // material={materials.Material}
        position={[0.333, -0.734, 0.043]}
      >
        <MeshTransmissionMaterial {...materialProps} />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube008.geometry}
        // material={materials.Material}
        position={[0.333, -0.734, 0.043]}
      >
        <MeshTransmissionMaterial {...materialProps} />
      </mesh>
    </group>
  )
}

useGLTF.preload("/mxk-logo.glb")
